### ISSUE TITLE
AEMET TODO

### ISSUE THREAD

**Issue by MalditoBarbudo** [emf-creaf/meteospain#1]
There are still things to do/improve/correct in the AEMET API:

  - [x] long/lat transf in `.get_info_aemet` can be done in one step.
  - [x] What happens when the stations selected are not in the data?? Because we filter afterwards. An error message
    indicating that the stations selected are not availbale and showing the available staions for that period.
  - [x] Conversion of dates to specific strings should be done in the .get_data_*, not in the service_options,
    that way an advanced user can create the option list by hand
  - [x] Add messages with the opendata texts from AEMET (how to use, cite...)
  - [x] Complete tests
      - [x] no stations data
