### ISSUE TITLE
General TODO

### ISSUE THREAD

**Issue by MalditoBarbudo** [emf-creaf/meteospain#2]
- [x] Workflows
    - [x] Review stations info workflow: We need the options for some, not for others.
    - [x] Tests for info workflow
    - [x] Tests for option functions
    - [x] Order of variables must be the same in all services
    - [x] Returned data must be ordered by timestamp & station_id in all services
  - [x] General package
    - [x] packages dependencies
    - [x] add README
    - [x] review functions examples
    - [x] added user agent to get requests
    - [x] CI (implemented with GitHub Actions)
    - [ ] ~~coverage~~
    - [x] pkgdown doc
    - [x] news.md
    - [x] collaboration guidelines
  - [x] Vignettes
    - [x] aemet
    - [x] meteoclimatic
    - [x] meteocat
    - [x] meteogalicia
    - [x] api limits and loops
  - [x] Services
    - [X] aemet
    - [X] meteoclimatic
    - [x] meteocat
    - [X] meteogalicia

**Comment by miquelcaceres** [comment]
Review examples of 'get_stations_info_from' and 'services_options'.

**Comment by MalditoBarbudo** [comment]
> Review examples of 'get_stations_info_from' and 'services_options'.

Added to the list

**Comment by MalditoBarbudo** [comment]
Implemented all 0.0.1 workflows, services and vignettes
