### ISSUE TITLE
AEMET TODO

### ISSUE THREAD

**Issue by MalditoBarbudo** [emf-creaf/meteospain#3]
Essential:

  - [x] service_options
  - [x] helpers
    - [x] path
    - [x] info
    - [x] meteo
  - [x] implement dispatcher in `get_meteo_from`
  - [x] implement dispatcher in get_stations_info_from
 
Others:

  - [ ] implement "monthly"
  - [x] try to identify the spurious error in aemet when building the package in GA, see #7

**Comment by MalditoBarbudo** [comment]
Ready for 0.0.1
